packaging_format = 2

id = "opencloud"
name = "OpenCloud"
description.en = "Online storage, file sharing platform"
description.fr = "Stockage en ligne, plateforme de partage de fichiers"

version = "7.5.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://opencloud.eu/en"
code = "https://github.com/opencloud-eu/opencloud"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = true
sso = true

disk = "100M"
ram.build = "250M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["cs", "de", "en", "es", "fr", "gl", "it"]
    default = "fr"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    extract = false
    rename = "opencloud"
    amd64.url = "https://github.com/opencloud-eu/opencloud/releases/download/v7.5.0/opencloud-7.5.0-linux-amd64"
    amd64.sha256 = "27d54e772b0fdbca148daa32b11ffb205b20174e4e934aebb5dfb7bef986f5f9"
    arm64.url = "https://github.com/opencloud-eu/opencloud/releases/download/v7.5.0/opencloud-7.5.0-linux-arm64"
    arm64.sha256 = "ffff43d70416e64ac2bd00066cd2901da3dcc27d9454c4e70e05790b7b822831"
    armhf.url = "https://github.com/opencloud-eu/opencloud/releases/download/v7.5.0/opencloud-7.5.0-linux-arm"
    armhf.sha256 = "96e88fa1fc93bf101ce7ec12fa8ffc3f316fdd13f0bda0032f80bf2d4cf64a8e"
    i386.url = "https://github.com/opencloud-eu/opencloud/releases/download/v7.5.0/opencloud-7.5.0-linux-386"
    i386.sha256 = "10129baf71b59a18ab6473ce045a089bd872b873b4c2fc8bcdf8f1ee9a6e2ec6"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^opencloud-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^opencloud-.*-linux-arm64$"
    autoupdate.asset.armhf = "^opencloud-.*-linux-arm$"
    autoupdate.asset.i386 = "^opencloud-.*-linux-386$"

    [resources.sources.draw-io]
    url = "https://github.com/opencloud-eu/web-extensions/releases/download/draw-io-v2.2.0/draw-io-2.2.0.zip"
    sha256 = "49c3aa32aa517f2a90f249b5470b38dc18b7d006841c442f64335d660b551d0c"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/opencloud-eu/web-extensions"
    autoupdate.version_regex = "^draw-io-v(.*)$"
    autoupdate.asset = "^draw-io-.*.zip"

    [resources.sources.external-sites]
    url = "https://github.com/opencloud-eu/web-extensions/releases/download/external-sites-v2.1.0/external-sites-2.1.0.zip"
    sha256 = "837dd36571ba010facc4c240f3e4369a6e142c675f20ec4b6657f1eaf241ec03"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/opencloud-eu/web-extensions"
    autoupdate.version_regex = "^external-sites-v(.*)$"
    autoupdate.asset = "^external-sites-.*.zip"

    [resources.sources.unzip]
    url = "https://github.com/opencloud-eu/web-extensions/releases/download/unzip-v2.1.0/unzip-2.1.0.zip"
    sha256 = "0bc876be618709a4a2a00cf0105287d4a14282c1600af8778eaa87cfabd6dbb6"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/opencloud-eu/web-extensions"
    autoupdate.version_regex = "^unzip-v(.*)$"
    autoupdate.asset = "^unzip-.*.zip"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    
    [resources.data_dir]
    subdirs = ["config", "idm", "idp", "nats", "proxy", "search", "storage"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/api"
    api.auth_header = false
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors"]

    [resources.ports]
