packaging_format = 2

id = "opencloud"
name = "OpenCloud"
description.en = "Online storage, file sharing platform"
description.fr = "Stockage en ligne, plateforme de partage de fichiers"

version = "6.1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://opencloud.eu/en"
code = "https://github.com/opencloud-eu/opencloud"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "100M"
ram.build = "250M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["cs", "de", "en", "es", "fr", "gl", "it"]
    default = "fr"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    extract = false
    rename = "opencloud"
    amd64.url = "https://github.com/opencloud-eu/opencloud/releases/download/v6.1.0/opencloud-6.1.0-linux-amd64"
    amd64.sha256 = "d1198359cc060b203c372d416f6889ce49174976f8cbd68ab76e616170f2511c"
    arm64.url = "https://github.com/opencloud-eu/opencloud/releases/download/v6.1.0/opencloud-6.1.0-linux-arm64"
    arm64.sha256 = "9d5e15db2833615dd2309b3ad36ceab2b42f7dd2a8c0f4035c9eaa6cde4d2fe0"
    armhf.url = "https://github.com/opencloud-eu/opencloud/releases/download/v6.1.0/opencloud-6.1.0-linux-arm"
    armhf.sha256 = "78fc4667e131349091a98ae85640686e3ab728b4f4b6c04f5b5d14ef89e0069e"
    i386.url = "https://github.com/opencloud-eu/opencloud/releases/download/v6.1.0/opencloud-6.1.0-linux-386"
    i386.sha256 = "66172d2551bf36884ed2e7ac5ff3b8326df2b6d67fb80b692fb36165d85184af"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^opencloud-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^opencloud-.*-linux-arm64$"
    autoupdate.asset.armhf = "^opencloud-.*-linux-arm$"
    autoupdate.asset.i386 = "^opencloud-.*-linux-386$"

    [resources.sources.draw-io]
    url = "https://github.com/opencloud-eu/web-extensions/releases/download/draw-io-v2.0.0/draw-io-2.0.0.zip"
    sha256 = "5af59d60ad244f609bf7fcc08ad07d22103eb94af363f1a3f47d7943f58f3fcd"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/opencloud-eu/web-extensions"
    autoupdate.version_regex = "^draw-io-v(.*)$"
    autoupdate.asset = "^draw-io-.*.zip"

    [resources.sources.external-sites]
    url = "https://github.com/opencloud-eu/web-extensions/releases/download/external-sites-v2.0.0/external-sites-2.0.0.zip"
    sha256 = "80a766fa5cbe933be7f7640da1f81d141211f2c9f29c2c4b803781f923c2a3c9"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/opencloud-eu/web-extensions"
    autoupdate.version_regex = "^external-sites-v(.*)$"
    autoupdate.asset = "^external-sites-.*.zip"

    [resources.sources.unzip]
    url = "https://github.com/opencloud-eu/web-extensions/releases/download/unzip-v2.0.0/unzip-2.0.0.zip"
    sha256 = "2ba1b70b509f202b6439f202068639c7ff317a668e844cfdcb7011eb051d62ba"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/opencloud-eu/web-extensions"
    autoupdate.version_regex = "^unzip-v(.*)$"
    autoupdate.asset = "^unzip-.*.zip"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    
    [resources.data_dir]
    subdirs = ["config", "idm", "idp", "nats", "proxy", "search", "storage"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/api"
    api.auth_header = false
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors"]

    [resources.ports]
