#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass  http://127.0.0.1:__PORT__;
  include     proxy_params_with_auth;

  more_set_headers "Strict-Transport-Security: 'max-age=31536000; includeSubDomains; preload' always";
  # Increase max upload size (required for Tus — without this, uploads over 1 MB fail)
  client_max_body_size 10G;

  # Disable buffering - essential for SSE
  proxy_buffering off;
  proxy_request_buffering off;

  # Extend timeouts for long connections
  proxy_read_timeout 3600s;
  proxy_send_timeout 3600s;
  keepalive_requests 100000;
  keepalive_timeout 5m;
  http2_max_concurrent_streams 512;
}
