#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

password=$YNH_APP_ARG_PASSWORD
ynh_app_setting_set --key=password --value=$password

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_setup_source --dest_dir="$install_dir/apps" --source_id="draw-io"
ynh_setup_source --dest_dir="$install_dir/apps" --source_id="external-sites"
ynh_setup_source --dest_dir="$install_dir/apps" --source_id="unzip"

chmod +x $install_dir/opencloud

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="File sharing platform" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/config/opencloud.env"

#=================================================
# INSTALL OPENCLOUD
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	./opencloud init --insecure=true --force-overwrite=true --admin-password=$password --config-path=$install_dir/
popd

chmod 400 "$install_dir/opencloud.yaml"
chown $app:$app "$install_dir/opencloud.yaml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
